%背包问题求解
%背包的重量
weight=CM.*DM;
%将背包重量除以10^6，减少动态规划计算量
weight_min=weight./1e7;
%转化为整数
weight_min_int=floor(weight_min);
FC_max_min=FC_max/1e7;
%kp01求解背包
%fmax最大收益
%x最优卸载结果
%[fmax,x]=kp01(weight_min_int,profit_arr,FC_max_min);
[fmax,x]=kp01(floor(weight_min),profit_arr,FC_max_min);

%根据最优卸载策略，最优发射功率和最优信道复用模式计算时延能耗等指标
tm_all_best=(1-x).*tm_loc_arr+x.*tm_off_arr;
em_all_best=(1-x).*em_loc_arr+x.*em_off_arr;
%所有CUE终端用户的总时延
tm_all_best_sum=sum(tm_all_best);
%所有CUE终端用户的总能耗
em_all_best_sum=sum(em_all_best);